### ISSUE TITLE
Babel 7 as Peer dependencies

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-jest#105]
https://github.com/vuejs/vue-jest/blob/master/package.json#L56

This line doesn't work
"babel-core@^6.25.0 || ^7.0.0-0"

Because @babel/core has changed of name as: "@babel/core"

**Comment by blackholegalaxy** [comment]
I think this should be considered quickly. Indeed the vue cli is moving fast and using jest with @babel/core setup instead of babel-core breaks the testing. So we need to keep babel-core as dependencies, especially for vue-jest.

Of cours it will mean breaking change for vue-jest as peer dependencies will move forward and dependencies toward babel plugins too.

**Comment by trollepierre** [comment]
Actually, I was wrong!
As ^7.0.0-0 is valid semver range
https://github.com/facebook/jest/issues/7061#issuecomment-425371766

I believe this issue can be closed

**Comment by blackholegalaxy** [comment]
the fact is we should not rely on babel-core anymore but @babel/core without any bridge. But I guess since jest is not ready this must have to wait

**Comment by trollepierre** [comment]
But a lot of projects are still using babel-core and I believe they will still be using it for a while.

**Comment by justinhelmer** [comment]
Yes, `babel-core@^7.0.0-0` is a valid semantic range that will allow any alpha or beta version or the [babel bridge](https://github.com/babel/babel-bridge) of babel 7: https://semver.npmjs.com/, which includes `@babel/core`.

This issue can be closed.

**Comment by snowyu** [comment]
No, It's not true.

**Comment by snowyu** [comment]
I got this error with babel@7.1.0:

```bash
Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```
This dependency:   `"@babel/plugin-transform-modules-commonjs": "^6.26.0"` force to babel@6 alaways!


```bash
$>npm ls
├─┬ vue-jest@2.6.0
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.26.2
│ │ ├─┬ babel-plugin-transform-strict-mode@6.24.1
│ │ │ ├── babel-runtime@6.26.0 deduped
│ │ │ └── babel-types@6.26.0 deduped
│ │ ├── babel-runtime@6.26.0 deduped
│ │ ├─┬ babel-template@6.26.0
│ │ │ ├── babel-runtime@6.26.0 deduped
│ │ │ ├── babel-traverse@6.26.0 deduped
│ │ │ ├── babel-types@6.26.0 deduped
│ │ │ ├── babylon@6.18.0 deduped
│ │ │ └── lodash@4.17.11 deduped
│ │ └── babel-types@6.26.0 deduped
```

**Comment by trollepierre** [comment]
@babel/plugin-transform-modules-commonjs looks like a dependency after Babel 7.

I don't understand your problem: do you want to upgrade to Babel 7? (so do it)
If not, you do not need anything with babel @7.1.0.

**Comment by snowyu** [comment]
sorry, typo, I've upgraded to babel7. The orignal code is:   https://github.com/vuejs/vue-jest/blob/4ac913d8a010fcdfa1c7fc5b4fe0cb5fc84eec79/package.json#L61

**Comment by trollepierre** [comment]
You don't have to worry about dependencies. Npm or yarn will manage this. You only need to focus on peer dependencies.
Here they are all fine.

**Comment by eddie-dunn** [comment]
Well, vue-jest doesn't work for me unless I install `babel-core@^7.0.0-0`. That should not be necessary as I have `@babel/core@^7.7.0` installed already.

```
$ yarn add --dev babel-jest @babel/core
...
warning " > vue-jest@3.0.5" has unmet peer dependency "babel-core@^6.25.0 || ^7.0.0-0".
```

**Comment by spietrek** [comment]
I am running into the same issue. Running babel-core 7.7.5.

`npm WARN vue-jest@3.0.5 requires a peer of babel-core@^6.25.0 || ^7.0.0-0 but none is installed. You must install peer dependencies yourself.`

**Comment by ThePeach** [comment]
ditto ☝️ 
`warning " > vue-jest@3.0.5" has unmet peer dependency "babel-core@^6.25.0 || ^7.0.0-0".`

currently I have `"@babel/core": "^7.8.4"`, `"jest": "^25.1.0"`, and `"vue-jest": "^3.0.3"`

**Comment by collyrooms** [comment]
same here 

warning " > vue-jest@3.0.5" has unmet peer dependency "babel-core@^6.25.0 || ^7.0.0-0".

package json is including     "@babel/core": "^7.8.4",     "jest": "^24.9.0",   "vue-jest": "^3.0.5"

**Comment by ajbkr** [comment]
Same here too...

`npm WARN vue-jest@3.0.7 requires a peer of babel-core@^6.25.0 || ^7.0.0-0 but none is installed.`

And...

```
@babel/core@7.12.10
jest@26.6.3
vue-jest@3.0.7
```

Additionally, when running my unit tests I also see many failed tests with output similar to the following:

```
 FAIL  src/components/__tests__/EmptyRouterView.test.js                                             
  ● Test suite failed to run                                                                        
                                                  
    Cannot find module 'babel-core'               
    Require stack:                                                                                  
    - /Users/ajb/src/rucka/node_modules/vue-jest/lib/compilers/babel-compiler.js                    
    - /Users/ajb/src/rucka/node_modules/vue-jest/lib/process.js                                     
    - /Users/ajb/src/rucka/node_modules/vue-jest/vue-jest.js 
    - /Users/ajb/src/rucka/node_modules/@jest/transform/build/ScriptTransformer.js                  
    - /Users/ajb/src/rucka/node_modules/@jest/transform/build/index.js                              
    - /Users/ajb/src/rucka/node_modules/jest-runtime/build/index.js                                 
    - /Users/ajb/src/rucka/node_modules/jest-runner/build/testWorker.js              
    - /Users/ajb/src/rucka/node_modules/jest-runner/node_modules/jest-worker/build/workers/processCh
ild.js                                                                                              
                                                  
    Require stack:                                                                                  
      node_modules/vue-jest/lib/compilers/babel-compiler.js                                         
      node_modules/vue-jest/lib/process.js        
      node_modules/vue-jest/vue-jest.js
      node_modules/@jest/transform/build/ScriptTransformer.js                                       
      node_modules/@jest/transform/build/index.js                                                   
      node_modules/jest-runtime/build/index.js                                                      
      node_modules/jest-runner/build/testWorker.js                                                  
      node_modules/jest-runner/node_modules/jest-worker/build/workers/processChild.js
                                                                                                    
      at Object.<anonymous> (node_modules/vue-jest/lib/compilers/babel-compiler.js:1:15)
```
