### ISSUE TITLE
Add support of custom block like the i18n

### ISSUE THREAD

**Issue by wlmzfx** [vuejs/vue-jest#116]
I am using the vue-i18n for my SFC, the SFC contains the i18n block, but current I am unable to create unit tests for the SFC due to unable to load the custom block i18n

**Comment by wlmzfx** [comment]
When can we have this feature?
Actually, I don't need to really verify the custom block like i18n, is there any possibility to ignore the custom block and not reporting errors?

**Comment by Ni55aN** [comment]
I have implemented a Jest transformer over `vue-jest`. 

```js
const VueJest = require('vue-jest');
const vueCompiler = require('vue-template-compiler')

module.exports = {
    process(src) {
        const { code, map } = VueJest.process(...arguments);
        const { customBlocks } = vueCompiler.parseComponent(src, { pad: true })
        const codeWithCustomBlocks = code + ';\n__vue__options__.customBlocks = '+JSON.stringify(customBlocks);
        
        return { code: codeWithCustomBlocks, map }
    }
}
```

This will add a `customBlocks` property to imported component

**Comment by kazupon** [comment]
@JessicaSachs 
I think we should offer some transform ways for custom blocks are needed, such as vue-i18n and gridsome.

**Comment by JessicaSachs** [comment]
What do you have in mind?

**Comment by kazupon** [comment]
I mean we want to support snapshot tests using custom blocks.
In vue-i18n case, i18n resource can define at `<i18n>` custom blocks, and it is injected to i18n resources on Vue instance with vue-loader / rollup-plugin-vue.
vue-jest is not supported custom blocks. 😞

**Comment by JessicaSachs** [comment]
Thanks for telling me your use case with snapshots.

I’ll give this a try. kazupon gave me a test repository to work against so
I’ll try to make it work in the next few days.

**Comment by JessicaSachs** [comment]
OK So I did something to support i18n blocks specifically in #227 but I think we can make the solution general and allow any custom block parser to return code.

**Comment by nogic1008** [comment]
Supported in [v4.0.0-beta.3](https://github.com/vuejs/vue-jest/releases/tag/v4.0.0-beta.3) or later.
You can find out how to use it in [README](https://github.com/vuejs/vue-jest#supporting-custom-blocks) or [vue-i18n transformer package](https://github.com/intlify/vue-i18n-jest).
