### ISSUE TITLE
[question] timeline on releasing 3.x?

### ISSUE THREAD

**Issue by justinhelmer** [vuejs/vue-jest#117]
Ultimately I need #111 for my current project. I am just using `git+http` protocol pointing to master for now, but would ideally use a published version of `vue-jest`.

**Comment by eddyerburgh** [comment]
Once https://github.com/vuejs/vue-jest/pull/115#issuecomment-428177095 is merged, which should be within a week.

**Comment by eddyerburgh** [comment]
Released https://github.com/vuejs/vue-jest/releases/tag/v3.0.0
