### ISSUE TITLE
[bug] vue-jest does not recognize jsx syntax

### ISSUE THREAD

**Issue by adamchenwei** [vuejs/vue-jest#126]
vue-jest seems not recognizing the jsx syntax when using `.vue` extension...
Wonder why?
Error below
<img width="832" alt="screen shot 2018-11-13 at 1 42 32 pm" src="https://user-images.githubusercontent.com/4201698/48435247-01e23c00-e74a-11e8-8e7b-466da5944a4f.png">

Reproduce 
```
git clone https://github.com/adamchenwei/boilerplate-webpack-babel-sass-storybook-vuejs.git
git checkout bug/jsx-not-working-with-jest
npm install
npm run test
see it throw error
```

**Comment by eddyerburgh** [comment]
JSX is handled correctly in master, which will be released as v4 (https://github.com/vuejs/vue-jest/pull/142).

**Comment by ssolders** [comment]
Ran into this and solved by using one of the latest commits:

```
"vue-jest": "git+ssh://git@github.com/vuejs/vue-jest#eab8d7956312cf81ec3f17fd152e3ef5d0cefdd4"
```

**Comment by Merott** [comment]
Ran into the same "unexpected token" error working on a Nuxt app, and it took me a lot of digging to find a solution.

This github issue is currently the first Google hit for "jest vue jsx" so here goes the solution, in case anyone (and the future me) finds it useful:

**Add [`@vue/babel-preset-jsx`](https://github.com/vuejs/jsx/tree/master/packages/babel-preset-jsx) to the babel config.**

I wonder if there's something else wrong with my config that's causing the problem though!
