### ISSUE TITLE
import 'some/style.css' failed

### ISSUE THREAD

**Issue by lefreet** [vuejs/vue-jest#133]
I'm writing a base component where depend on third party UI component library；
such as:
```js
import ElInput from 'element-ui/lib/input'
import 'element-ui/lib/theme-chalk/input.css'
```
it run successful；

but when i try run the test by `jest`， it return the error ' SyntaxError: Unexpected token .' and I see the css code was wrapped as a module；

![image](https://user-images.githubusercontent.com/25679627/49348484-b84d9700-f6e0-11e8-8ed1-3cc786293db6.png)

Is there some loader config to should I change ?

thanks.

**Comment by eddyerburgh** [comment]
Yes you need to add a transformer to handle css files:

```js
jest: {
  transform: {
    "^.+\\.js$": "babel-jest",
    "^.+\\.vue$": "vue-jest",
    ".+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$": "jest-transform-stub"
  }
  // ..
}
```

**Comment by thinckx** [comment]
In my case, the module wasn't being transformed, so I also had to add:

```
"moduleNameMapper": {
    // ...
    "^.+.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$": "jest-transform-stub"
}
```
