### ISSUE TITLE
babelConfig option value is not respected if babel.config.js is found

### ISSUE THREAD

**Issue by TomaszChrosniak** [vuejs/vue-jest#135]
https://github.com/vuejs/vue-jest/blob/98882455e2ade39efe9b8cf683b13a5f71ffb7c2/lib/load-babel-config.js#L33-L35

The order of operations in the babel-config-loader makes it impossible to skip configuring babel if the `babel.config.js` file is found.

The README states that setting the `babelConfig` property to `false` on the `globals[vue-jest]` object should result in babel being skipped entirely.

Similarly, if one wishes to provide a different path to the config file or a config object, they will also be ignored.

**Comment by LinusBorg** [comment]
@eddyerburgh @TomaszChrosniak This was fixed and release so it should be closed.
