### ISSUE TITLE
Coverage report doesn't show for Vue components that don't have executable JS code

### ISSUE THREAD

**Issue by saifulss** [vuejs/vue-jest#147]
When running Jest for test coverage, a Vue component (Single File Component) won't show up in the coverage report unless it has at least 1 line of executable JS code.

An example of executable JS code, is adding a method to the component (even if you don't use the method). Once there's at least 1 line, the file will show up in the coverage report.

I use the coverage report to see which files have yet to be covered by the coverage report. Even the simple Vue components with no executable JS code.

**Comment by danielistyo** [comment]
This bug appear again in my code. 
`"vue-jest": "3.0.5",`

My component code:
```
<template>
	<div class="back-to-top" @click="backToTop">
		<img v-lazy="'/general/img/icons/ic_voucher_back_to_top.svg'" />
	</div>
</template>

<script>
export default {
	props: {
		backToTop: {
			type: Function,
			required: true
		}
	}
};
</script>
```

It doesn't have coverage report. If I add one method, I will have coverage report
