### ISSUE TITLE
Update ts-jest peer dependency

### ISSUE THREAD

**Issue by noelheesen** [vuejs/vue-jest#167]
Hello,

I'm getting a warning about an incorrect peer dep of ts-jest. This package still uses ts-jest 23 while [ts-jest](https://github.com/kulshekhar/ts-jest) is now in version 24.0.0 which includes [jest](https://github.com/facebook/jest) version ^24. Any chance the ts-jest peer dep can be upgraded in the next release?

**Comment by AlbertBrand** [comment]
Hi @eddyerburgh, I created one: https://github.com/vuejs/vue-jest/pull/169

**Comment by eddyerburgh** [comment]
Fixed in #169
