### ISSUE TITLE
Vuejs + Jest : “SyntaxError: Unexpected token <”

### ISSUE THREAD

**Issue by JawedHook** [vuejs/vue-jest#185]
I have a Vue file which imports a Vue file from node_modules. This file seems to not be recognize as a vue file when imported and doesn't use vue-jest.

I tried to use an htmlLoader, but doesn't work either.

Here is the error I get :

```
path/node_modules/vue-loading-spinner/src/components/Jumper.vue:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<template>                 
SyntaxError: Unexpected token <
```

Here is my jest.conf.js :
```
const path = require('path')

module.exports = {
  rootDir: path.resolve(__dirname, '../../'),
  moduleFileExtensions: [
    'js',
    'vue',
    'html'
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  transform: {
    '^.+\\.js$': '<rootDir>/node_modules/babel-jest',
    '.*\\.vue$': '<rootDir>/node_modules/vue-jest',
    "^.+\\.html$": "<rootDir>/test/utils/htmlLoader.js"
  },
  testPathIgnorePatterns: [
    "<rootDir>/node_modules/"
  ],
  modulePaths: [
    "<rootDir>"
  ],
  setupFiles: ['<rootDir>/test/unit/setup'],
  testMatch: [
    '<rootDir>/(test/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx))'
  ]
}
```
And here is my test file ( I know there is no test in this file, but not necessary at the moment if I can mount my component ) :
```
import { shallowMount } from "@vue/test-utils"
import Card from '@/components/Card'
import { propsSet } from '../../datas/components/Card'
import Brace from 'vue-bulma-brace'

describe('FreeSql Unit Tests', () => {
    test('FreeSql : Display correct', () => {
        
        const wrapper = shallowMount(FreeSql, {
            propsData:{
                ...propsSet
            },
            stubs:{
                Brace
            }
        })
    })
})
```

Thanks for your help.

**Comment by LinusBorg** [comment]
Judging from the error message referring to a file in a node_modules package:
```
path/node_modules/vue-loading-spinner/src/components/Jumper.vue:1
```
We can see that your .vue file itself is recognized fine, but jest seems to not transform stuff from node_modules.

And that's indeed the default behaviour:

https://jestjs.io/docs/en/23.x/configuration#transformignorepatterns-array-string

**Solution**

Excempt this package from the `transformIgnorePatterns` option with a negatiuve lookahead:

```json
{
  "transformIgnorePatterns": ["/node_modules/(?!vue-loading-spinner)"]
}
```

**Comment by JawedHook** [comment]
@LinusBorg That works perfectly, thank you for your help. :)

**Comment by manuel-84** [comment]
same error, no working solutions found yet

**Comment by LinusBorg** [comment]
Well, your case doesn't seem specialty it should work with a matxhing transformIgnorePattern. 

I don't see anything else to do or try.what pattern did you try?

**Comment by manuel-84** [comment]
> Well, your case doesn't seem special, it should work with a matching transformIgnorePatternike described in m previous comment.
> 
> I don't see anything else to do or try.what pattern did you try?

for transform i tried `^.+\\.vue$` and `^(.*).vue$` and some variations
for transformIgnorePattern `/node_modules/(?!(v-snackbars)/)` and little variations

I don't know if it matters that i'm on windows machine

**Comment by adityaswaroop823** [comment]
hiii @manuel-84  i am facing exactly same issue , Were you able to fix this

**Comment by manuel-84** [comment]
> hiii @manuel-84 i am facing exactly same issue , Were you able to fix this

hi, no the only way was to not use the module and instead create a custom component 'v-snackbars' using the source from its own repo
