### ISSUE TITLE
npm / yarn points to eddy's fork instead of this package

### ISSUE THREAD

**Issue by kamok** [vuejs/vue-jest#194]
When you do `npm i vue-jest` or `yarn add vue-jest`, you'll get eddy's fork instead. https://github.com/eddyerburgh/vue-jest

I'm assuming this is not expected. 

Ended up doing this in package.json instead
```
    "vue-jest": "https://github.com/vuejs/vue-jest.git",
```

**Comment by eddyerburgh** [comment]
Thanks, this is a hangover from when the repo was under my name.

Fixed in bf3becec7f7eb92ca6ded93f028956e96f674637
