### ISSUE TITLE
Importing a CSS file in a component throws an error

### ISSUE THREAD

**Issue by darthmeme** [vuejs/vue-jest#199]
I scaffolded out a `@vue/cli` project with Jest included. Then installed Bootstrap, and included the CSS file into the `HelloWorld.vue` component.

When running `yarn unit:test`, I get the following error:
![image](https://user-images.githubusercontent.com/42481527/65300129-2440b380-dbbe-11e9-95c2-46992e96c282.png)

Jest config (in `package.json`) includes:
```
".+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$": "jest-transform-stub",
```

Repo: https://github.com/darthmeme/vue-jest-import-css

**Comment by cp3r** [comment]
Jest doesn't apply transforms to node_modules by default. You can solve this by using `moduleNameMapper` in your jest config file:
```
{
  "jest": {
    // ..
    "moduleNameMapper": {
      "^.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$": "jest-transform-stub"
    }
  }
}
```

From jest-transform-stub [FAQ](https://github.com/eddyerburgh/jest-transform-stub#faq)

**Comment by darthmeme** [comment]
@cp3r - hey, thanks for the reply! I recently found that out, but forgot about this issue. Closing.
