### ISSUE TITLE
adding vue-jest to transform svg in vue testing

### ISSUE THREAD

**Issue by engmagdy87** [vuejs/vue-jest#202]
I added svg-jest to test vue component
when I follow the instruction of adding loader to jest
https://vue-svg-loader.js.org/faq.html#how-to-use-this-loader-with-jest

I got this error appears
![Screenshot-20191009142507-708x279](https://user-images.githubusercontent.com/8473421/66484353-15f00400-eaa7-11e9-9f2f-93ded22361d0.png)

**Comment by florianschepp** [comment]
@engmagdy87 did you come up with a solution here? Would love to know :)

**Comment by engmagdy87** [comment]
@florianschepp 
I added the svg image as a stub

```
const wrapper = shallowMount(Component, {
  stubs: ["svgImage"]
})
```
