### ISSUE TITLE
Don't inject $style for functional component with module css

### ISSUE THREAD

**Issue by palpich** [vuejs/vue-jest#207]
If create a functional component as 
```
export default {
  functional: true,

  render: function (createElement, context) {
    // ...
  }
}
```
without section `template`, styles don't inject.

I think, this happen, because [this check](https://github.com/vuejs/vue-jest/blob/master/lib/process.js#L103) does not take into account the way to create a functional component with property `functional: true`

I can do PR for fix that, but I don't know a good solution.

https://github.com/palpich/vue-jest-bug-reproduction

**Comment by utlime** [comment]
@palpich added temporary fix https://github.com/utlime/vue-jest/commit/22605a92e4d34cf2ee88b0e06f372669491bab58

update version if needed
"vue-jest": "github:utlime/vue-jest",

**Comment by palpich** [comment]
@utlime thank you for your fix!

I don't close this issue to fix this bug in production.

**Comment by palpich** [comment]
https://github.com/vuejs/vue-jest/pull/236
