### ISSUE TITLE
Idea: put unit tests inside of SFCs

### ISSUE THREAD

**Issue by parker-codes** [vuejs/vue-jest#219]
Hey all, I've simply had an idea and would like to get opinions on the validity and ease of it. I believe this is the best repo to propose it.

The coding industry used to adamantly separate things by it's responsibility (such as markdown vs logic vs styling). Now Vue and others encourage a different take - componentization. We have a template, script, and style tag that allows us to only focus on that specific thing. I think this is great. 

My issue is that unit tests do not follow this concept. I just maintain a duplicated file structure, which has been annoying at times when renaming or moving component files. 

What I propose is that an additional script tag could exist with some attribute related to testing that can be used to house the unit tests. The current module system allows files to import themselves and I believe has protections against recursion.

I've posted this idea elsewhere (probably Twitter) and got no bite, but I really think it has potential. I largely gravitate towards this because I also work in Rust which has this concept as first-class. 

What I'm not looking to hear are rebuttals about how we don't need to change things that already work. Change can be _very_ good.

**Comment by JessicaSachs** [comment]
Hey @google-mac I've also heard this idea floating around. It's worth considering and I'm intrigued by it as well :-)

I think something that might ease your pain quicker than we can add support for something like a custom block (`<test>` etc) is that jest actually supports putting your tests next to your source code or in a __test__ folder sibling to your source code.

https://jestjs.io/docs/en/configuration#testmatch-arraystring

**Comment by google-mac** [comment]
@JessicaSachs Yeah, I have typically just included a sibling spec file for each component, which is closer to a matching setup (like a Counter.vue and Counter.spec.js). 

I'm glad I'm not the only one that's thought of this. Hopefully more traction could grow if it's a good thing.

**Comment by lmiller1990** [comment]
No traction on this for 1 year - going to close due to inactivity.
