### ISSUE TITLE
Missing release `3.0.5`

### ISSUE THREAD

**Issue by chenxeed** [vuejs/vue-jest#243]
Hello. I saw in the [npm package](https://www.npmjs.com/package/vue-jest), the version is `3.0.5`. However I couldn't found it in the [release](https://github.com/vuejs/vue-jest/releases).

Can anyone help me confirm if this is intended?

**Comment by lmiller1990** [comment]
Most likely whoever released it (I have not done a release for v3 since taking over this repo) forgot.

I also cannot see a tag for this - I have no way to confirm if this was intended. 🤔 

At this point I would recommend upgrading to v4 beta - is that possible in your project?

**Comment by lmiller1990** [comment]
I released 3.0.6, which is the latest from the v3 branch.

Please upgrade to v4 if you can, though.
