### ISSUE TITLE
Need support for code splitting

### ISSUE THREAD

**Issue by chenxeed** [vuejs/vue-jest#25]
Hi!

Currently I'm trying to code split my vue component with this way:

// App.vue
```
<style scoped src="./template/style.scss" lang="scss"></style>
<template src="./template/index.html"></template>
<script src="./script/index.js" type="text/javascript"></script>
```

And it seems that the `vue-jest` doesn't render the template. When I mount the component and check the `vm.$el.innerHTML` it's empty.

I see the comment in the docs:
https://vue-test-utils.vuejs.org/en/guides/testing-SFCs-with-jest.html
```
Note: vue-jest currently does not support all the features of vue-loader, for example custom block support and style loading. In addition, some webpack-specific features such as code-splitting are not supported either. 
```

So is the problem I faced is regarding the code splitting not supported yet?

**Comment by andrey-mordasov** [comment]
Vote for this. I'm experiencing the same issue.

**Comment by IgorKonovalov** [comment]
Huge pain for me as I'm working in a project with 1000+ lines components (don't ask me why)

**Comment by LinusBorg** [comment]
You can use `"babel-plugin-dynamic-import-node` to make node work with `import()` statements.

**Comment by garytryan** [comment]
@LinusBorg this was also suggested as a solution for the same problem with jest-vue-preprocessor. This solution doesn't work for either case, as far as I can tell.

**Comment by andrey-mordasov** [comment]
We noticed that this issue is not relevant with latest code version.

**Comment by LinusBorg** [comment]
@eddyerburgh this can be closed, I think. Not to be solved in vue-jest
