### ISSUE TITLE
Vuejs + Jest : “SyntaxError: Unexpected token .”

### ISSUE THREAD

**Issue by Nolin-Lin** [vuejs/vue-jest#257]
I have a Vue file which imports a Vue file from node_modules. This file seems to not be recognize as a vue file when imported and doesn't use vue-jest.

Here is the error I get :
```
/Users/nolin/Desktop/bnad-mk/front_code/mk/node_modules/_@riophae_vue-treeselect@0.3.0@@riophae/vue-treeselect/dist/vue-treeselect.css:18
    .vue-treeselect-helper-hide {
    ^
    SyntaxError: Unexpected token .
      15 | <script>
      16 | import Treeselect from '@riophae/vue-treeselect'
   > 17 | import '@riophae/vue-treeselect/dist/vue-treeselect.css'
           | ^
      18 | 
      19 | export default {
```

Here is my jest.conf.js :

```
module.exports = {
  moduleFileExtensions: ['js', 'jsx', 'json', 'vue'],
  transform: {
    '^.+\\.vue$': 'vue-jest',
    '.+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$':
      'jest-transform-stub',
    '^.+\\.jsx?$': 'babel-jest',
    '\\.(css|scss|sass|less)$': 'identity-obj-proxy'
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1'
  },
  snapshotSerializers: ['jest-serializer-vue'],
  testMatch: [
    '**/tests/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx)'
  ],
  collectCoverageFrom: ['src/utils/**/*.{js,vue}', '!src/utils/auth.js', '!src/utils/request.js', 'src/components/**/*.{js,vue}'],
  coverageDirectory: '<rootDir>/tests/unit/coverage',
  // 'collectCoverage': true,
  'coverageReporters': [
    'lcov',
    'text-summary'
  ],
  testURL: 'http://localhost/',
  'transformIgnorePatterns': ['/node_modules/(?!@riophae/vue-treeselect)']
}
```

**Comment by lmiller1990** [comment]
Hm, you should be able to work around that with `transformIgnorePatterns`. Maybe your `transformIgnorePatterns` is wrong? Looking at [the Jest docs](https://jestjs.io/docs/en/tutorial-react-native#transformignorepatterns-customization), they do it like this: `"node_modules/(?!(react-native|my-project|react-native-button)/)"`. Maybe you need to do `  'transformIgnorePatterns': ['/node_modules/(?!@riophae/vue-treeselect)/']` (note the trailing slash). It that the `identity-obj-proxy` is not getting applied to the `'@riophae/vue-treeselect/dist/vue-treeselect.css'`.

**Comment by Nolin-Lin** [comment]
> Hm, you should be able to work around that with `transformIgnorePatterns`. Maybe your `transformIgnorePatterns` is wrong? Looking at [the Jest docs](https://jestjs.io/docs/en/tutorial-react-native#transformignorepatterns-customization), they do it like this: `"node_modules/(?!(react-native|my-project|react-native-button)/)"`. Maybe you need to do ` 'transformIgnorePatterns': ['/node_modules/(?!@riophae/vue-treeselect)/']` (note the trailing slash). It that the `identity-obj-proxy` is not getting applied to the `'@riophae/vue-treeselect/dist/vue-treeselect.css'`.

Wow, it worked.
Thank you for taking the time to help me solve the problem
