### ISSUE TITLE
Ensure working with Vue 3 + custom babel config

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-jest#258]
Issue found here: https://github.com/vuejs/vue-cli/issues/5714

**Comment by lmiller1990** [comment]
Should be good in 5.0.0-alpha.2

**Comment by Amour1688** [comment]
I got error in 5.0.0-aplha.3.

![image](https://user-images.githubusercontent.com/31695475/89897761-1fd81b80-dc12-11ea-8120-256fedf02de6.png)

![image](https://user-images.githubusercontent.com/31695475/89897974-7ba2a480-dc12-11ea-8416-2ca4515dc2da.png)

My Babel config

https://github.com/vueComponent/ant-design-vue/blob/feat-vue3/.babelrc

**Comment by lmiller1990** [comment]
I will take a look at your project. I guess it isn't respecting `.babelrc`? 🤔

**Comment by Amour1688** [comment]
> I will take a look at your project. I guess it isn't respecting `.babelrc`? 🤔

yeah, it works when I renamed it to `babel.config.js`.

**Comment by lmiller1990** [comment]
I think the later versions of babel don't support `.babelrc`. Is this a good enough fix for your project? Or do we need to leave this open?

**Comment by Wizard67** [comment]
How to suport [`<script setup>`](https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-script-setup.md#transform-api)?

**Comment by lmiller1990** [comment]
I have not tried this yet. I was hoping it would "just work" - the SFC compiler (should) take care of it, mostly.

What happens when you tried it?

**Comment by Wizard67** [comment]
> I have not tried this yet. I was hoping it would "just work" - the SFC compiler (should) take care of it, mostly.
> 
> What happens when you tried it?

`@vue/runtime-core` warns `[Vue warn]: Property "x" was accessed during render but is not defined on instance.` when I run the test script.

reproduction link: https://github.com/Wizard67/vue3-test

**Comment by lmiller1990** [comment]
Yep, we need to do a check for `<script setup>`. This should be fairly easy, I will look into it tomorrow or Friday.

**Comment by jolting** [comment]
<script setup> works. The example needs to be updated a bit because the syntax changed.
```
<script setup lang="ts">
import { defineProps,  ref } from 'vue'

const props = defineProps({
  msg: String
})

const count = ref<number>(0)
</script>
```

**Comment by lmiller1990** [comment]
Script setup keeps changing. We should update the dependencies here and make sure it works with the latest version.
