### ISSUE TITLE
Source lines 

### ISSUE THREAD

**Issue by nirkki** [vuejs/vue-jest#27]
Coverage report source lines are not correct. 
[Clean project](https://github.com/vuejs-templates/webpack/issues/1062)  created with ```vue init webpack jest-test``` produce faulty sourcecode line references for the coverage report.

**Comment by eddyerburgh** [comment]
I've removed cacheing in 2.1.1, can you see if this solved the issue?

**Comment by bodrick** [comment]
So I have run into this issue also with a few SFCs I have written tests for.  The coverage report comes back as having missing lines that don't even exist.  I'm using the latest version of vue-jest (2.2.1).

The text report shows in my one component has having uncovered lines for 35,36,43 but the code file has 35 lines total.

Could this be something related to SCSS and global imports I have or something else altogether.

**Comment by eddyerburgh** [comment]
I'm closing this issue, but if somebody else has an issue with source maps, __please create a runnable reproduction in a GitHub repository__ and open a new issue.
