### ISSUE TITLE
Make babel-jest and ts-jest peer Deps

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-jest#281]
Ref: https://github.com/vuejs/vue-jest/pull/262#issuecomment-691859510

**Comment by dpogue** [comment]
Note that npm v7 will [install peerDependencies again](https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md) so this might not end up working the way you want it to

**Comment by sodatea** [comment]
If I understand correctly, optional peer dependencies won't be affected.
