### ISSUE TITLE
`TypeError: tr.configsFor is not a function` causes on ts-jest@26.4.2 and above

### ISSUE THREAD

**Issue by nogic1008** [vuejs/vue-jest#294]
In this package, `TsJestTransformer.configsFor()` is used in [utils/getTsJestConfig](https://github.com/vuejs/vue-jest/blob/master/lib/utils.js#L66) function.
But, unfortunately, this method has been deleted on v26.4.2, kulshekhar/ts-jest#2020.
So `TypeError: tr.configsFor is not a function` error causes on test.
## Workaround
downgrade ts-jest version to 26.4.1 or below in `package-lock.json`(npm) or `yarn.lock`(yarn)
## Fixes
plz merge #284 and release
## Refs
- [GitHub Actions Log](https://github.com/nogic1008/nuxt-ts-template/runs/1350362381)

**Comment by zigomir** [comment]
Ugh, thanks @nogic1008 for opening this. I've spent so much time figuring out what's going on here. +💯

**Comment by ahnpnl** [comment]
This can be fixed by reverting https://github.com/kulshekhar/ts-jest/pull/2020 . `ts-jest` will have the next release 26.4.4 soon which can include the revert.

**Comment by ahnpnl** [comment]
`ts-jest` 26.4.4 is out, this issue should be fixed now

**Comment by nogic1008** [comment]
@ahnpnl Thank you for your works! 
[GitHub Actions Log](https://github.com/nogic1008/nuxt-ts-template/runs/1371489177)
