### ISSUE TITLE
What about less support?

### ISSUE THREAD

**Issue by prokhororlov** [vuejs/vue-jest#314]
There's a last style preprocessor left, when are you going to add less support?
Is there any way to use less in vue files using jest?

**Comment by Badbreaddead** [comment]
@prokhororlov Why have you closed the issue? Was it added?

**Comment by jolting** [comment]
@Badbreaddead compiler-sfc will handle this in vue3. Vue3 support currently depends on #268. Are you using Vue2 or Vue3?

**Comment by Badbreaddead** [comment]
@jolting thank you for answering. I am on Vue2 unfortunately. I guess support for vue2 is out of discussion, isn't it?

**Comment by jolting** [comment]
Vue2 is in LTS, so the utility new vue2 features would have a short time horizon. Just a friendly nudge towards more community effort focused on vue3 functionality. I'm sure patches are welcome for vue2.
