### ISSUE TITLE
Can`t combine css modules and postcss

### ISSUE THREAD

**Issue by gpyshenko** [vuejs/vue-jest#340]
I get error in my vue file if i combine css modules and lang="postcss".

```vue
<style module lang="postcss">
.Logo {
    &__image {
        height: auto;
    }
}
</style>
```

My error
```
No PostCSS Config found in: path_to_project
```
My config postcss in `nuxt.config.js`

```javascript
build: {
      postcss: {
          'plugins': {
              'postcss-import': true,
              'precss': {},
          },
      },
},
```

If i add postcss.config.js then process dont stop.

Versions:
vue-jest: "^3.0.7"

**Comment by lmiller1990** [comment]
Can you try upgrading to 4.x? 3.x has not had a release for a long time.

**Comment by imolater** [comment]
@gpyshenko Hi, i'm running into same problem. This is because an endless cycle (while) in postcss-compiler file. I made a [fork](https://github.com/imolater/vue-jest/commit/7b410e88cd7ec2dc65d5b2725b7ef9a6467e8764) with fix.

**Comment by gpyshenko** [comment]
> @gpyshenko Hi, i'm running into same problem. This is because an endless cycle (while) in postcss-compiler file. I made a [fork](https://github.com/imolater/vue-jest/commit/7b410e88cd7ec2dc65d5b2725b7ef9a6467e8764) with fix.
