### ISSUE TITLE
Whether to support vue3 tsx and related configuration

### ISSUE THREAD

**Issue by uinio** [vuejs/vue-jest#359]

**Comment by lmiller1990** [comment]
I don't understand what this issue is supposed to mean. Are you asking a question? It's not clear what action should be taken.

I'm going to close this until you provide more information. Happy to reopen after you provide more info on your idea/request.

**Comment by cuebit** [comment]
@lmiller1990 seeing similar issues being created by this user across the ecosystem 🤦🏻‍♂️
