### ISSUE TITLE
Code coverage doesn't work on files linked with "src="

### ISSUE THREAD

**Issue by Toilal** [vuejs/vue-jest#36]
I try to add code coverage to my project, but I use `src=` and it doesn't seem to be supported.

Maybe it's related to sourcemaps missing (https://github.com/eddyerburgh/vue-jest/pull/29#issuecomment-347252861).

**Comment by eddyerburgh** [comment]
Yeah, sorry. Source maps are missing at the moment. I'll add them soon

**Comment by eddyerburgh** [comment]
This was fixed in #131
