### ISSUE TITLE
vue-jest@4.0.1 config undefined TypeError

### ISSUE THREAD

**Issue by pazderka** [vuejs/vue-jest#362]
I have came across the versions `4.0.0` and `4.0.1` of vue-jest. I assume it should be possible to use these versions as usual, as they seem to be marked as stable versions.

In vue-jest@4.0.1 (and probably in 4.0.0 as well) there is an issue with running tests. Tests fail with `TypeError: Cannot destructure property 'config' of 'undefined' as it is undefined.` when you try to import a vue component into a test file.

Reproduction is here: https://github.com/pazderka/vue-jest-error-repro
just run `npm install` and `npm run test` and the error will occur.

The same repo is working when you install vue-jest@3.0.7

**Comment by nogic1008** [comment]
@pazderka 
`vue-jest@4` does not support `jest@27.x` yet, also not `vue-jest@3.x` and `vue-jest@5.x`.
Please downgrade jest to `26.x` as workaround, or wait #355 and #343.

**Comment by nogic1008** [comment]
Close this issue because duplicates with #267
