### ISSUE TITLE
Vue 3 TS + Jest + Vue Jest unable to resolve dependency tree

### ISSUE THREAD

**Issue by horia16** [vuejs/vue-jest#376]
What happens when we run `npm install vue-jest@next --save-dev`:
![image](https://user-images.githubusercontent.com/32731652/130670432-9961bb0b-4814-48d9-9920-1812e91ef596.png)

Dependencies:
![image](https://user-images.githubusercontent.com/32731652/130670511-d3b513b8-f703-4570-9dd7-db258efa7d48.png)

Also downgrading or forcing a lower version of jest does not work
![image](https://user-images.githubusercontent.com/32731652/130670860-749f816f-7f01-46e6-a502-71042dab0700.png)

It will not load the transformer either way and not recognize the module.

**Comment by alexrafuse** [comment]
Did you fix this? I'm running into the same issue.
