### ISSUE TITLE
When is v5 release coming?

### ISSUE THREAD

**Issue by ninjabhishek** [vuejs/vue-jest#437]
The rc candidate for v5 has been sitting around for quite some time now. When is the first final release expected? vue cli is creating the new project with rc candidates as dependencies and it's really tough to get code to production in corporate environment as these are caught by different check tools in place.

It's hight time even v27 is published for vue3

**Comment by nogic1008** [comment]
@ninjabhishek 
As README shows, you can use `@vue/vue3-jest@27.x` instead.
