### ISSUE TITLE
Cannot resolve module when using --watch flag

### ISSUE THREAD

**Issue by rmartins90** [vuejs/vue-jest#46]
I'm using `moduleNameMapper` property on jest.conf.js to define alias to match the same as webpack, jest works when I run entire suite `npm run unit` but when I use `--watch` flag (or `-o`) process hangs with message `Determining test suites to run...`. I've discovered that this happens because jest can't resolve alias paths.

**Comment by eddyerburgh** [comment]
Thanks for the bug report.

Looks like this is a Jest issue—https://github.com/facebook/jest/issues/4883

Could you try going to node_modules/jest-resolve/build/index.js, and adding console.error(error) before every line that says throw error?
