### ISSUE TITLE
Functional component with template only

### ISSUE THREAD

**Issue by noamcore** [vuejs/vue-jest#47]
As requested, I bring the issue to this repo.

The problem is that `<template functional>` is not passed as a functional template, so I'm unable to test by passing the context object to the `mount` from the vue-test-utils.

vuejs/vue-test-utils#360

**Comment by eddyerburgh** [comment]
Thanks for the report, we're transferring the repo at the moment but once it's moved over I'll look into this

**Comment by jeremyzahner** [comment]
@eddyerburgh Any updates on this? Can i help anyhow?

**Comment by eddyerburgh** [comment]
Yes, if you would like to address this issue, I'm happy to review a PR.
Sorry I can't give more guidance at the moment, I haven't had time to look
into the issue

**Comment by noamcore** [comment]
I'll try to look at this too. I'm not familiar contributing to open-source projects and this could be a start for me.
