### ISSUE TITLE
Tests failing with `No coverage available for <vue files only>`

### ISSUE THREAD

**Issue by ccamarat** [vuejs/vue-jest#48]
Originally posted at [vuejs-templates/webpack](https://github.com/vuejs-templates/webpack/issues/1260); steps to reproduce the issue are in that post.

Tests were working on Saturday; they started failing last night (PST). JavaScript-only Jest tests without Vue components pass with coverage enabled. Vue tests pass if coverage is disabled.

Note: The setup for this is defect to simply use the vue-cli to install the [webpack template](https://github.com/vuejs-templates/webpack) and run `npm run test`. I'm using Windows 10.

**Comment by BeauAgst** [comment]
@ccamarat I ran into this issue this morning, and couldn't work out for the life of me what the problem was. All of my files were doubling up in the coverage report too, was that happening to you? 

I ended up back-tracking over what I'd done since yesterday, and I'd moved some tests into a directory inside of `specs`. Apparently, for my setup this was a big no-no, and moving them back out of that directory and into the root fixed it. I'm not sure if that could be a possibility for you?

**Comment by ccamarat** [comment]
I apologize for the delay.

Yes, items in the /components are showing up twice in the report!

I've done a few small experiments:

* Moved the spec up one level to \test\unit per @BeauAgst's suggestion - No change
* Upgraded from Node 8.9.3 / NPM 5.5.1 to Node 8.9.4 / NPM 5.6.0 - No change
* Tried same project on Lubuntu - Issue goes away
* Tried same project on Bash for Windows - Issue goes away

Whatever this is it looks Windows-specific.

**Comment by ccamarat** [comment]
I was able to throw a couple hours at this one today. I've got a successful (if limited) workaround and was able to determine that the issue was introduced with Jest v22.0.0. I also have some info that *may* help someone track this down or resolve.

**Work Around**
Place the Jest configuration directly inside package.json following the [vue test utils jest-example][3]

**Troubleshooting Activities**
* Tried the [Vue Test Utils Jest Example][1]: Issue not present
* Compared the [Vue Webpack Template][2] looking for differences
  1. Copied the config file from the template to the test utils and updated `unit` script to use it - issue not present
  2. With above config file in place, updated Jest from `^21.1.0` to Jest `22.0.0` - issue appears (experimented with several explicit 22.* versions; issue was introduced in 22.0.0, which unfortunately has a [long changelist][4] ).
  3. Backed out config file change from #i (using example's package.json config) - issue not present

I futzed around with the config file for a while. For a bit I was hopeful that the `path.resolve()` was somehow involved because removing it caused the problem to disappear. I'm pretty sure this was a red herring (but not completely sure); the coverage report was simply "All files: Unknown".

The last piece of information while reviewing the coverage report itself. As @BeauAgst pointed out, the coverage report lists the tested Vue files twice, while the untested Vue files are only listed once. I'm not sure how many core devs use Windows so I'll post a picture:
![image](https://user-images.githubusercontent.com/1820184/36360168-4bf6816c-14d6-11e8-9772-6dad8473705b.png) I find it interesting that [a file with no branches][5] would report 50% coverage (while it's peer shows 100% covered with 0% overall).

[1]: https://github.com/eddyerburgh/vue-test-utils-jest-example
[2]: https://github.com/vuejs-templates/webpack
[3]: https://github.com/eddyerburgh/vue-test-utils-jest-example/blob/master/package.json#L78
[4]: https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-2200
[5]: https://github.com/vuejs-templates/webpack/blob/develop/template/src/components/HelloWorld.vue

**Comment by eddyerburgh** [comment]
I've removed cacheing in 2.1.1, can you see if this solved the issue?

**Comment by eddyerburgh** [comment]
If you're still having the second issue, please open a new issue with a reproduction that I can run.

**Comment by ccamarat** [comment]
Thanks. I was away from jest for a bit and lost track of this. I tried it again the other day and did not notice the duplicated report anymore. Thanks again!
