### ISSUE TITLE
Wrong coverage lines due to missing template

### ISSUE THREAD

**Issue by meufel** [vuejs/vue-jest#500]
Hey everyone,

first of all thanks for your work!

I'm facing a problem since the latest version of vue2-jest **29.1.0**:

### Problem Description
The coverage resulting from my tests does not contain the `<template>` part of my SFC-files.
This leads to
1. **wrong line numbers** inside the cli text summary
2. incomplete file representation inside the cobertura html report

Especially the 1) has a significant impact on my daily work writing tests.

**_SFC:_**
![sfc](https://user-images.githubusercontent.com/39161228/191005654-c10ac1fc-0533-42e4-8ae6-8293b4b75a62.png)

**_Text Summary:_**
![text coverage](https://user-images.githubusercontent.com/39161228/191005686-26a6bc91-0939-495c-8d78-de33e425ed7e.png)

**_HTML Report:_**
![html coverage](https://user-images.githubusercontent.com/39161228/191005699-18d620a4-8e26-46e6-8175-ab26a94fe51d.png)

### Reproduction
The following project shows the impact when running the tests: https://github.com/meufel/vue-jest-coverage-repro

### Reseach Results
Looking at the changes coming with script setup support I noted that the related [commit](https://github.com/vuejs/vue-jest/commit/7f2287cf71d0f40f0a53d3e4e3d60604a9b26f8e) contains a [snapshot](https://github.com/vuejs/vue-jest/commit/7f2287cf71d0f40f0a53d3e4e3d60604a9b26f8e#diff-331261aac2a4dc9bb5ee3ef97a03c3f66d88826913979251445c38b7684f1a5d), which also lost its template part (resp. its `//` representation).

Since I have to stick with v29.0.0 for now, is there an option to reenable the correct line number generation?

**Comment by meufel** [comment]
Resolved by https://github.com/vuejs/vue-jest/pull/516. Thank You!

**Comment by Rodigee** [comment]
I'm still seeing a similar issue, even when on 29.2.2.

**Comment by meufel** [comment]
It may be a jest caching issue. I can reproduce the problem when only updating vue-jest but keeping the jest version:

`npm install -D @vue/vue2-jest@29.2.2 && npm test`

Running `npm test -- --clearCache` once fixes the coverage report.
