### ISSUE TITLE
scss/sass warning

### ISSUE THREAD

**Issue by km-tr** [vuejs/vue-jest#57]
Currently the following message is displayed in the output every vue component containing scss or sass. 

`[vue-jest]: scss and sass are not currently compiled by vue-jest.`

I think that it can be displayed once at once.

What do you think?

**Comment by eddyerburgh** [comment]
Yes, I can see that being annoying when you're compiling multiple components that contain scss.

Would you like to make a PR?

**Comment by km-tr** [comment]
@eddyerburgh https://github.com/vuejs/vue-jest/pull/59
I made PR.
