### ISSUE TITLE
Error compile sass

### ISSUE THREAD

**Issue by brunoosilva** [vuejs/vue-jest#67]
**Do you want to request a _feature_ or report a _bug_?**

BUG

**What is the current behavior?**

Don't work with sintaxe `sass` in Vue Component File with style. If I remove the `--coverage` or remove children flag, it works. For exemple, class with children class:

```css
<style lang="scss" scoped>
.test{
    color: red;
    .testChildren{
        color: black;
    }
}
</style>
```
***Command***: `jest --config test/unit/jest.conf.js --coverage`

***Error***:
![image](https://user-images.githubusercontent.com/3465257/37286264-3224da3e-25e0-11e8-9feb-9735cf3b1976.png)

**Please provide your exact Jest configuration**

```js
const path = require('path')

module.exports = {
  rootDir: path.resolve(__dirname, '../../'),
  moduleFileExtensions: [
    'js',
    'json',
    'vue'
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1'
  },
  transform: {
    '^.+\\.js$': '<rootDir>/node_modules/babel-jest',
    '.*\\.(vue)$': '<rootDir>/node_modules/vue-jest'
  },
  snapshotSerializers: ['<rootDir>/node_modules/jest-serializer-vue'],
  setupFiles: ['<rootDir>/test/unit/setup'],
  coverageDirectory: '<rootDir>/test/unit/coverage',
  collectCoverageFrom: [
    'src/**/*.{js,vue}',
    '!src/**/*.spec.{js,vue}',
    '!**/node_modules/**'
  ],
};

```

**Run `npx envinfo --preset jest` in your project directory and paste the
results here**

```shell
  System:
    OS: OS X El Capitan 10.11.6
    CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Binaries:
    Node: 8.9.3
    Yarn: 1.3.2
    npm: 5.6.0
  npmPackages:
    jest:
      wanted: ^22.1.4
      installed: 22.4.2
```

**Comment by jeremyzahner** [comment]
@brunoosilva Do you still have this issue with the current implementation of the SASS/SCSS compiler?

**Comment by brunoosilva** [comment]
@jeremyzahner I upgraded to version from `vue-jest@^2.0.0` to `vue-jest@^2.5.0` and `node-sass@^4.7.2` to `node-sass@^4.9.0`, now it's working.

Thank you and sorry for the late reply.
