### ISSUE TITLE
How to choose the CSS for a component?

### ISSUE THREAD

**Issue by nikolay-govorov** [vuejs/vue-jest#72]
I want to configure testing with screenshots for vue components. To prepare a snapshot, I need to select not only HTML but also CSS from the component. How can I do that?

**Comment by eddyerburgh** [comment]
Hi, full CSS isn't supported yet.

Are you using a library to generate a snapshot with HTML and CSS?

**Comment by nikolay-govorov** [comment]
Screenshots, not snapshots. I made one for myself. I can in HTML and CSS to create the screenshots and based on them to test the appearance of components, but I don't know how to select CSS from the vue-component

**Comment by eddyerburgh** [comment]
Unless somebody else implements it, vue-jest won't support CSS. You should use vue-loader to generate screenshots
