### ISSUE TITLE
flag to disable warnings (or scss warnings only)

### ISSUE THREAD

**Issue by ilyaztsv** [vuejs/vue-jest#75]
Hello!

What do you think about to add a flag to disable all warnings?

Or, for example, a flag to disable only `scss` warnings (from `scss-compiler.js`)?

I use `webpack aliases` in my components and during `npm run test` of my project I see to many logs like this.: `CSS is not fully supported by vue-jest, so some features will throw errors. Webpack aliases are a common cause of errors.`

I've create the following example project: https://github.com/ilyaztsv/vue-jest-warnings

### Steps to reproduce:

```
npm i
npm run test 2>&1 | grep 'SCSS is not fully supported'
```

### Screenshot to view issue

<img width="1423" alt="screen shot 2018-03-26 at 15 40 25" src="https://user-images.githubusercontent.com/3539802/37895615-089891b0-310c-11e8-88d1-19d37b645da8.png">

The example project also related to #69 issue.

If the suggestion suits you then I can create a PR.

**Comment by viljamis** [comment]
Was just looking for a solution to disable the SCSS warnings as well.

**Comment by eddyerburgh** [comment]
I've published a flag `hideStyleWarn` in 2.4.0.

```js
  // package.json
  {
    "jest": {
      "globals": {
        "vue-jest": {
          "hideStyleWarn": true
        }
      }
    }
  }
  ```

**Comment by ilyaztsv** [comment]
Amazing!

**Comment by ilyaztsv** [comment]
@eddyerburgh thanks for `hideStyleWarn`, but it solves #69 only.
I still have `SCSS is not fully supported by vue-jest, so some features will throw errors. Webpack aliases are a common cause of errors.` warnings.

I can disable `SCSS is not fully supported ...` warnings if I set `experimentalCSSCompile = false`.

What do you think about if `hideStyleWarn` also disable `SCSS` warnings?

**Comment by ilyaztsv** [comment]
As I can see the issue of `SCSS is not fully supported by vue-jest, so some features will throw errors. Webpack aliases are a common cause of errors.` is resolver in `v.2.5.0` (8f1ff0b)
