### ISSUE TITLE
Using external css

### ISSUE THREAD

**Issue by hewIngram** [vuejs/vue-jest#76]
Hello, 

I'm looking at adding unit test coverage to my vue app but I'm having trouble fetching my css. I'm currently using external css in my components:

``` <style module scoped src='./Example.css' /> ```

Which isn't working, I spotted @danielbastos11 's PR adding support for css modules and was wondering if vue-jest can deal with external css yet? If not I'm happy to extend the work in https://github.com/vuejs/vue-jest/pull/50 to allow external css files and open a PR for it.

Thanks

**Comment by eddyerburgh** [comment]
We  don't support  external CSS. A PR would be very welcome!

**Comment by rmartins90** [comment]
does this help @hewIngram? https://facebook.github.io/jest/docs/en/webpack.html#handling-static-assets

**Comment by lancetharper** [comment]
I think I've run into a similar (or might be the same) issue.

```
<style module>
@import "some/file.css"
</style>
```
`wrapper.vm.$style` = {}.

If I change it to:
```
<style module>
@import "some/file.css"

.test {
  color: purple;
}
</style>
```
`wrapper.vm.$style` = { test: 'test' }

Does this look to be the same issue?

**Comment by hewIngram** [comment]
Just opened a PR that reads the src attribute of a style tag so that vue-jest can deal with external css.

https://github.com/vuejs/vue-jest/pull/158
