### ISSUE TITLE
Yarn / NPM

### ISSUE THREAD

**Issue by jeremyzahner** [vuejs/vue-jest#80]
It seems like there is two lockfiles right now. @eddyerburgh which one is actually supposed to be used? Also, the scripts in the `package.json` run as npm, while Circle executes yarn.

**Comment by eddyerburgh** [comment]
Thanks for pointing this out. We should only have yarn.lock file.

Although we should use npm run on Circle.

**Comment by eddyerburgh** [comment]
Fixed in 6ff4cb541d6d182cbc580be4c39b4bed8888cecf
