### ISSUE TITLE
TSConfig defaults is a dead code path

### ISSUE THREAD

**Issue by dcherman** [vuejs/vue-jest#84]
The default tsconfig here https://github.com/vuejs/vue-jest/blob/9cef21f9dfde2753ec49b17b8668345f9d508134/lib/compilers/typescript-compiler.js#L8-L30

Will never be hit since `loadSync` provides an empty set of defaults if no `tsconfig.json` is found

https://github.com/TypeStrong/tsconfig/blob/5281eafd459a574343bab1bfb8d2ec004cd07355/src/tsconfig.ts#L142-L148

Which means this condition is never falsy in any scenario

https://github.com/vuejs/vue-jest/blob/9cef21f9dfde2753ec49b17b8668345f9d508134/lib/compilers/typescript-compiler.js#L39-L43

We should probably swap that out for `resolveSync` to see if we would have found a `tsconfig.json` before attempting to load it if we want these defaults to be used.

**Comment by dcherman** [comment]
Alternatively, it looks like they also provide `path` on the returned value if it's found from `loadSync`, else it's `undefined`.  Can easily check to see if a path exists instead.

**Comment by eddyerburgh** [comment]
Thanks for the bug report. Would you like to make a PR?

**Comment by dcherman** [comment]
@eddyerburgh Yep, already done.  Just had to write some tests / refactor the code a bit to do so.
