### ISSUE TITLE
node_modules really required in config?

### ISSUE THREAD

**Issue by marinko-peso** [vuejs/vue-jest#94]
@eddyerburgh I saw the config in https://github.com/vuejs-templates/webpack/blob/develop/template/test/unit/jest.conf.js and was wondering is it really required to have ```<rootDir>/node_modules/``` before babel-jest and vue-jest. Same applies here.
What I mean is that once you define rootDir jest automatically knows that all plugins (modules) are by default located in node_modules, and therefore only specifying babel-jest and vue-jest should get them loaded properly. Same applies for snapshotSerializers where jest-serializer-vue itself should be enough.
I am simply trying to understand cause from my point of view if jest.config.js (we should probably rename it in vue-cli link I sent from conf to config) is not placed inside root already simply setting up proper rootDir should be enough?
Any info would be helpful, thanks ahead! :-)

**Comment by eddyerburgh** [comment]
Yes, I believe you can just set:

```
"jest": {
  "transform": {
    "^.+\\.js$": "babel-jest",
    "^.+\\.vue$": "vue-jest"
  }
}
```

This is [how I configure Jest in my projects](https://github.com/eddyerburgh/vue-hackernews/blob/chapter-3/package.json#L55).

We could update the README to use the shortened version.

Would you like to make a PR?

**Comment by marinko-peso** [comment]
Yes sir, so just to confirm I could get 2 PR's up:
- here to update README for the shortened version
- and maybe one to update configuration at vue-cli to use shortened version? Reason why I came to this is cause I have a friend who started using jest using vue-cli as example and got super confused with node_modules so want to help others not to get confused the same way :-)

Thanks for the quick response btw!
