### ISSUE TITLE
Tagged template strings are not supported

### ISSUE THREAD

**Issue by mjss** [vuejs/vue-jest#98]
If tagged template strings are used, test suit will fail with following error:
```
Tagged template strings are not supported. Use `transforms: { templateString: false }` to skip transformation and disable this error, or `transforms: { dangerousTaggedTemplateString: true }` if you know what you're doing (1:303)

      at Node.initialise (node_modules/vue-template-es2015-compiler/buble.js:12998:10)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)

```
Apparently, this error message is from `buble.js`.
It seems that `vue-jest` uses `vue-template-es2015-compiler`, and  `vue-template-es2015-compiler` uses `buble`.
But neither `vue-jest` nor `vue-template-es2015-compiler` explains whether it is necessary and how to configure `buble`.

Is it possible to resolve this in `vue-jest`?
Any fixes or explanations are appreciated. Thank you.

I created a sample project to illustrate the issue. Steps to reproduce:
1. clone https://github.com/mjss/vue-jest-with-tagged-template
2. run `npm test:unit`

**Comment by danrocha** [comment]
@mjss did you manage to solve this somehow?
I am trying to test  some components which use tagged template strings and I am having these errors with Jest:

```
Tagged template strings are not supported. Use `transforms: { templateString: false }` to skip transformation and disable this error, or `transforms: { dangerousTaggedTemplateString: true }` if you know what you're doing
```

The error is coming from an `<apollo-query>` component with a `gql` string.

**Comment by mjss** [comment]
@danrocha No I didn't resolve this issue back then. I am not sure whether the newer versions of `vue-jest` or `vue-template-es2015-compiler` supports tagged template strings now. Tagged template strings were not a must-have in our project, thus we just removed them.

**Comment by axwalker** [comment]
@danrocha I'm in the same boat as you - trying to test components that use `<apollo-query>` + `gql` - did you find a solution in the end?

**Comment by danrocha** [comment]
No, I gave up on the apollo components a while ago!

**Comment by FRSgit** [comment]
Hey, I've added a fix (or rather - I've extended the `vue-jest` library to address this issue) and created a PR #288.

#### If you want to use it in your project where you have `vue-jest` as *a direct dependency*:
- remove the package with `npm uninstall vue-jest` or `yarn remove vue-jest`,
- add it back from my fork `npm install --save-dev https://github.com/FRSource/vue-jest#feat-add-compile-template-options` or `yarn add -D https://github.com/FRSource/vue-jest#feat-add-compile-template-options`.

#### Or if you're using `vue-jest` *via `@vue/cli-plugin-unit-jest`*:
- add this to your `package.json`:
  ```
  "resolutions": {
    "**/vue-jest": "git+https://github.com/FRSource/vue-jest#feat-add-compile-template-options"
  }
  ```
-  run `yarn install`.

And ofc stay updated on when the #288 would get merged into the master to switch back to the official `vue-jest` package!
